# Generated by Django 3.2.25 on 2024-05-22 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=255, unique=True)),
                ('english_name', models.CharField(blank=True, max_length=255, null=True)),
                ('values', models.TextField(blank=True, null=True)),
                ('audience', models.TextField(blank=True, null=True)),
                ('competitors', models.TextField(blank=True, null=True)),
                ('regions', models.CharField(default='中国大陆', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(blank=True, max_length=255, null=True)),
                ('usp', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketing.brand')),
                ('personas', models.ManyToManyField(related_name='products', to='marketing.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='emotion_tags',
            field=models.ManyToManyField(blank=True, related_name='brands', to='marketing.EmotionTag'),
        ),
        migrations.AddField(
            model_name='brand',
            name='industry_tags',
            field=models.ManyToManyField(blank=True, related_name='brands', to='marketing.IndustryTag'),
        ),
    ]
