# Generated by Django 3.2.25 on 2024-05-25 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0003_alter_brand_chinese_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='personas',
            field=models.ManyToManyField(blank=True, related_name='brands', to='marketing.Persona'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('objectives', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenarios', models.JSONField(blank=True, null=True)),
                ('brands', models.ManyToManyField(blank=True, related_name='campaigns', to='marketing.Brand')),
                ('creator', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('personas', models.ManyToManyField(blank=True, related_name='campaigns', to='marketing.Persona')),
                ('products', models.ManyToManyField(blank=True, related_name='campaigns', to='marketing.Product')),
            ],
        ),
    ]
