# Generated by Django 3.2.25 on 2024-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('wechat_openID', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('wechat_nickname', models.CharField(blank=True, max_length=128, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('个人用户', '个人用户'), ('企业用户', '企业用户')], max_length=32)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='指定该用户所属的组', related_name='custom_user_groups', related_query_name='user', to='auth.Group', verbose_name='用户组')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='指定用户的特定权限', related_name='custom_user_permissions', related_query_name='user', to='auth.Permission', verbose_name='用户权限')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
