# Generated by Django 3.2.25 on 2026-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfvalue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfvaluereport',
            name='qa_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
